---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
      #Install PJP

      echo "apt-get -qq update"
      sudo apt-get -qq update

      echo "sudo apt-get -qq -y install php5"
      sudo apt-get -qq -y install php5

      echo "apt-get -qq clean"
      sudo apt-get -qq clean

      #Lint the PHP source
      echo
      echo "Lint the PHP source"
      php -l *.php
- name: Deploy Prod(Bluemix) & Prod(AWS)
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: APP_NAME
    type: text
  - name: S3_BUCKET
    type: text
  - name: AWS_SECRET_ACCESS_KEY
    type: secure
  - name: AWS_ACCESS_KEY_ID
    type: secure
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: Pipeline
    script: "#!/bin/bash\n\necho \"Install Ansible\"\nsetup_tools/install_ansible.sh\
      \ \n\necho \"Run Ansible playbook\"\nansible-playbook --module-path=./ansible-elastic-beanstalk/library/\
      \ .playbook.yml\n\necho \"Ansible playbook complete\"\n"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
